### PR TITLE
Updates for OCaml 4.02.2

### PR DESCRIPTION
**Pull request by talex5**
* Don't apply patch to add GC hooks - 4.02.2 has some of its own.
* Get headers from new location.

### CODE REVIEW

**Comment by Drup** [comment]
I can't manage to make this work. `make xen-ocaml-build` fails. Here is a pastebin of the failure: http://pastebin.archlinux.fr/1333907

Apparently, something is going wrong in the line 
```
make -j${NJOBS} UNIX_OR_WIN32=unix NATIVECCCOMPOPTS="-DNATIVE_CODE ${CFLAGS}" NATIVECCPROFOPTS="-DNATIVE_CODE ${CFLAGS}" libasmrun.a
```

**Comment by avsm** [comment]
I think we should put a patch in for this as well http://caml.inria.fr/mantis/view.php?id=6919

**Comment by talex5** [comment]
@Drup your pastebin link appears empty to me...

**Comment by Drup** [comment]
Here it is, I forgot to change the date again: http://pastebin.archlinux.fr/1366841

**Comment by Drup** [comment]
(the error is probably line 91)

**Comment by talex5** [comment]
What pins do you have? I'm building with:

    $ opam pin
    mirage-xen.dev            path  /home/tal/work/cubieboard/platform
    mirage-xen-ocaml.2.3.1    path  /home/tal/work/cubieboard/platform
    mirage-xen-posix.2.3.1    path  /home/tal/work/cubieboard/platform

**Comment by Drup** [comment]
```
certify.~unknown         (uninstalled)  git  https://github.com/yomimono/ocaml-certify.git         
cohttp.0.18.3                           git  https://github.com/mirage/ocaml-cohttp.git            
mirage-seal.0.3.1                       git  /home/gabriel/source/mirage-seal                      
mirage-unix.2.3.1                       git  https://github.com/talex5/mirage-platform.git#gc-hooks
mirage-xen.2.3.2         (uninstalled)  git  https://github.com/talex5/mirage-platform.git#gc-hooks
mirage-xen-ocaml.2.3.1   (uninstalled)  git  https://github.com/talex5/mirage-platform.git#gc-hooks
mirage-xen-posix.2.3.1                  git  https://github.com/talex5/mirage-platform.git#gc-hooks
```

**Comment by talex5** [comment]
/home/gabriel/.opam/mirage/lib/pkgconfig/../../include/mirage-xen-posix/include/time.h:16:8: erreur: unknown type name ‘s_time_t’
     extern s_time_t not_running_time;

Further up in `time.h` we have `#include_next <time.h>`. The compiler args include `-isystem/home/gabriel/.opam/mirage/lib/pkgconfig/../../include/minios-xen`, so you should have a file `/home/gabriel/.opam/mirage/lib/pkgconfig/../../include/minios-xen/time.h` with the definition:

    typedef int64_t s_time_t;

**Comment by Drup** [comment]
I confirm I have the file with the definition in `.opam/mirage/lib/pkgconfig/../../include/minios-xen/`.

**Comment by talex5** [comment]
Any other `time.h` files in the other directories that could be shadowing it? Try adding `-H` to the `CFLAGS` in `build.sh` so it shows what it's including. Compile with `make NJOBS=1` to avoid confusion.

**Comment by Drup** [comment]
Here is the log: https://gist.github.com/anonymous/0d16defb89c4a2fa9fcb
I'm starting to look at it but nobody jumps out for now.

**Comment by talex5** [comment]
I'm a bit confused. Your output for `dynlink.c` starts:

    gcc -I../byterun -DCAML_NAME_SPACE -DNATIVE_CODE -DTARGET_amd64 -DSYS_linux  -DNATIVE_CODE -H -Wno-attributes -momit-leaf-frame-pointer -mfancy-math-387  -DSYS_xen -USYS_linux   -isystem/home/gabriel/.opam/mirage/lib/pkgconfig/../../include/minios-xen -isystem/home/gabriel/.opam/mirage/lib/pkgconfig/../../include/minios-xen/posix -m64 -mno-red-zone -fno-reorder-blocks -fno-stack-protector -fno-asynchronous-unwind-tables -nostdinc -isystem /usr/lib/gcc/x86_64-unknown-linux-gnu/5.1.0/include -U__linux__ -U__FreeBSD__ -U__sun__ -U__linux -D__MINIOS__ -I/home/gabriel/.opam/mirage/lib/pkgconfig/../../include/mirage-xen-posix/include -I/home/gabriel/.opam/mirage/include    -I /home/gabriel/.opam/mirage/include/mirage-xen/include   -c -o dynlink.o dynlink.c
    . /home/gabriel/.opam/mirage/lib/pkgconfig/../../include/mirage-xen-posix/include/errno.h
    .. /home/gabriel/.opam/mirage/include/mirage-xen/include/errno.h
    ... /home/gabriel/.opam/mirage/include/minios-xen/errno.h
    .... /home/gabriel/.opam/mirage/include/minios-xen/errno-base.h
    . /home/gabriel/.opam/mirage/lib/pkgconfig/../../include/mirage-xen-posix/include/stdio.h

But `dynlink.c` starts with `#include <stddef.h>`. So why is it loading `errno.h`?

My output is (as expected):

    gcc -I../byterun -DCAML_NAME_SPACE -DNATIVE_CODE -DTARGET_amd64 -DSYS_linux  -DNATIVE_CODE -H -Wno-attributes -momit-leaf-frame-pointer -mfancy-math-387  -DSYS_xen -USYS_linux   -isystem/home/tal/.opam/4.02.2/lib/pkgconfig/../../include/minios-xen -isystem/home/tal/.opam/4.02.2/lib/pkgconfig/../../include/minios-xen/posix -m64 -mno-red-zone -fno-reorder-blocks -fno-stack-protector -fno-asynchronous-unwind-tables -nostdinc -isystem /usr/lib/gcc/x86_64-unknown-linux-gnu/5.1.0/include -U__linux__ -U__FreeBSD__ -U__sun__ -U__linux -D__MINIOS__ -I/home/tal/.opam/4.02.2/lib/pkgconfig/../../include/mirage-xen-posix/include -I/home/tal/.opam/4.02.2/include    -I /home/tal/.opam/4.02.2/include/mirage-xen/include   -c -o dynlink.o dynlink.c
    . /usr/lib/gcc/x86_64-unknown-linux-gnu/5.1.0/include/stddef.h
    . /home/tal/.opam/4.02.2/lib/pkgconfig/../../include/mirage-xen-posix/include/stdlib.h
    .. /home/tal/.opam/4.02.2/lib/pkgconfig/../../include/mirage-xen-posix/include/sys/cdefs.h
    .. /home/tal/.opam/4.02.2/lib/pkgconfig/../../include/mirage-xen-posix/include/sys/types.h

**Comment by Drup** [comment]
I'm equally confused. Could it be a gcc version issue ? I'm on 5.1.0

**Comment by talex5** [comment]
I'm on 5.1.0 too (and on Arch).

**Comment by Drup** [comment]
I switched back to 4.02.1, both the current release and your version works there.

**Comment by Drup** [comment]
After investigation with @talex5, the error was caused by a `include/mirage-xen` directory left over from a very old mirage package. For some reason, the compilation is still trying to include it, even if it should not exist anymore.

**Comment by talex5** [comment]
It seems this was caused by first installing and removing a very old version of mirage-xen. This put some files in the old `${prefix}/include/mirage-xen/include` directory and failed to remove them on uninstall.

The new version doesn't create this directory I think, but does still add it to the search path (in `mirage-xen-ocaml-bindings.pc` and `mirage-xen.pc`).

**Comment by talex5** [comment]
OK to merge this now? I think the OCaml bug @avsm mentioned will be fixed in 4.02.3 and we shouldn't do it here.

**Comment by Drup** [comment]
Yes, it was fixed.

**Pull request merged**
