### PR TITLE
remove module OS.Env, which had a stub implementation for argv.

### PR DESCRIPTION
**Pull request by hannesm**
The way to get boot parameters is the default_argv device

### CODE REVIEW

**Comment by hannesm** [comment]
see https://github.com/pqwy/mirage-os-shim/pull/2 and https://github.com/mirage/mirage-solo5/pull/18

**Comment by hannesm** [comment]
any opinion? @mirage/core

**Comment by djs55** [comment]
The approach sounds good to me. Does it need to be merged and released
simultaneously with other changes? I could potentially do that later today.
I've not looked in detail, but does the default_argv device work on Xen?
IIRC the argv turns up somewhere like the boot info page.

**Comment by samoht** [comment]
LGTM

**Comment by hannesm** [comment]
On 16/06/2017 08:25, David Scott wrote:
> The approach sounds good to me. Does it need to be merged and released
> simultaneously with other changes?

The only user of OS.Env.argv is ocl-stubblr -- where I opened a PR (and
this needs to be released first to not break compilations).

> I could potentially do that later today.
> I've not looked in detail, but does the default_argv device work on Xen?
> IIRC the argv turns up somewhere like the boot info page.

Yes, in mirage.ml we have the argv_xen device which uses
mirage-bootvar-xen, and seems to work smoothly.

**Comment by yomimono** [comment]
This is still a good idea but unfortunately it conflicts now.  If you rebase, we should merge IMO :)

**Comment by hannesm** [comment]
this has as prerequisite https://github.com/pqwy/mirage-os-shim/pull/2 -- which we do not have control over

**Comment by hannesm** [comment]
this is useless as is, will rework for mirage-xen/mirage-solo5/mirage-unix once we've control over mirage-os-shim (i mailed david whether we can get the repository into the mirage organisation)

**Pull request closed without merging**
