### PR TITLE
Implement times and sysconf

### PR DESCRIPTION
**Pull request by talex5**
This makes `Sys.time` work, which makes Irmin happy.

### CODE REVIEW

**Comment by samoht** [comment]
Can someone review that patch? @djs55 maybe?

**Comment by MagnusS** [comment]
According to [this](http://caml.inria.fr/pub/docs/manual-ocaml/libref/Sys.html) `Sys.time` should return processor time, but it looks like this implementation returns monotonic time since the VM started without [subtracting time](https://github.com/mirage/mirage-platform/pull/134/files#diff-0bdc2dc4d2720cf0bf5a3144ee744e34R186) spent blocked/sleeping. Could be confusing for applications that try to use `Sys.time` to measure CPU time :-)

**Comment by avsm** [comment]
Good point -- keeping a low level timer in minios makes sense here...

**Comment by talex5** [comment]
I've added a `not_running_time` offset in mirage-xen, which is increased each time `block_domain` runs. The advantage of doing it here is that we don't have to do it once for each arch.

**Comment by samoht** [comment]
That's great! Can you check if we can remove the OS.Xs call from https://github.com/MagnusS/mirage-stats-demo with that patch?

**Comment by MagnusS** [comment]
@samoht In mirage-stats-demo I try to measure the time passed since Xen began booting the domain until the first user specified code is executed in the unikernel. Timers started in the unikernel would be inaccurate as the unikernel would already be running to start the timer :-) But perhaps we could get the timestamp from somewhere else? I created and issue to discuss it [here](https://github.com/MagnusS/mirage-stats-demo/issues/3)

(the OS.Xs calls are [here](https://github.com/MagnusS/mirage-stats-demo/blob/master/dispatch.ml#L109))

**Comment by talex5** [comment]
@MagnusS BTW, compiling the stats demo gives `Error: Unbound module Opam_manifest`.

**Comment by samoht** [comment]
need to run `make depend`

**Comment by talex5** [comment]
Oh, cool - I didn't know you could add custom make rules!

**Comment by samoht** [comment]
yea, but I think the current mechanism is not expressive enough yet. Would be great to to just have to run `make` in that case. If you have some ideas, please feel free to contribute to https://github.com/mirage/mirage/issues/412 and/or to send patches :-)

**Comment by talex5** [comment]
Can this be merged now?

**Comment by samoht** [comment]
Done, thanks!

**Pull request merged**
