### PR TITLE
build 4.04 in mirage-xen-ocaml

### PR DESCRIPTION
**Pull request by yomimono**
This allows `mirage-xen-ocaml` to be installed on switches using 4.04.0 , and unikernels built in that configuration to boot and run under xen.  I admit to having very little idea what I'm doing here, and I'd appreciate a review of these changes.

Fixes #173 .

### CODE REVIEW

**Comment by yomimono** [comment]
Got an LGTM from @hannesm via IRC and a `conduit_mirage` example unikernel from `mirage-skeleton` built with it served 1,000 requests, so I'll call it good enough to merge.  Counterarguments welcome ;)

**Comment by samoht** [comment]
The `./configure: not found` error on Windows doesn't look very good :-)

**Comment by hannesm** [comment]
oh, I guess we can now claim to be a "xen" or "whateveryoulikebutnotunix" platform, since https://github.com/ocaml/ocaml/pull/674 got into 4.04! (we should do this, and as well in ocaml-freestanding /cc @mato) -- this is unless it breaks elsewhere

**Comment by yomimono** [comment]
@samoht: Yes, I agree!  So I filed #174 , which has information about how long this has been happening in this repository.

**Comment by yomimono** [comment]
@hannesm: file an issue for that?  I think it will be forgotten as a comment on a merged PR.

**Pull request merged**
